## SQL_Analysis

- Database Connection
- Data Loading
- Database Validation

In [1]:
import mysql.connector
import pandas as pd

In [2]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="ash3524"
)

conn

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute("""
CREATE DATABASE IF NOT EXISTS olist_ecommerce
""")

conn.commit()

In [5]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="ash3524",
    database="olist_ecommerce"
)

cursor = conn.cursor()

In [6]:
cursor.execute("SELECT DATABASE();")

cursor.fetchone()

('olist_ecommerce',)

In [7]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(50) PRIMARY KEY,
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix INT,
    customer_city VARCHAR(100),
    customer_state VARCHAR(10)
)
""")

conn.commit()

In [8]:
cursor.execute("SHOW TABLES")

cursor.fetchall()

[('category_translation',),
 ('customers',),
 ('order_items',),
 ('orders',),
 ('payments',),
 ('products',),
 ('reviews',),
 ('sellers',)]

In [9]:
from sqlalchemy import create_engine

In [10]:
engine = create_engine(
    "mysql+pymysql://root:ash3524@localhost/olist_ecommerce"
)

In [11]:
customers = pd.read_csv(
    "customers_clean.csv"
)

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP

In [12]:
customers.shape

(99441, 5)

In [13]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [14]:
customers.to_sql(
    'customers',con=engine,if_exists='replace',index=False
)

99441

We're creating the SQL database from scratch, so replace makes sure an old/incomplete table doesn't interfere

In [15]:
query = """
SELECT COUNT(*) AS total_costomers
FROM customers;
"""
pd.read_sql(query,engine)

   total_costomers
0            99441

In [16]:
query = """
SELECT *
FROM customers
LIMIT 5;
"""
pd.read_sql(query,engine)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP

In [17]:
orders = pd.read_csv(
    "orders_clean.csv"
)

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [18]:
orders.shape

(99441, 8)

In [19]:
date_col = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_col:
    orders[col] = pd.to_datetime(orders[col],errors='coerce')

In [20]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [21]:
orders.to_sql(
    'orders',con=engine,
    if_exists='replace',
    index=False
)

99441

In [22]:
order_items = pd.read_csv(
    "order_items_clean.csv"
)

order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [23]:
order_items.shape

(112650, 7)

In [24]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [25]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [26]:
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'],errors='coerce')

In [27]:
order_items.to_sql(
    'order_items',con=engine,if_exists='replace',index=False
)

112650

In [28]:
pd.read_sql(
    """
SELECT COUNT(*) AS total_order_items
FROM order_items;
""",
engine
)

   total_order_items
0             112650

In [29]:
pd.read_sql(
    """
    SELECT *
    FROM order_items
    LIMIT 5;
    """,
    engine
)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [30]:
pd.read_sql(
    """
    SELECT COUNT(DISTINCT order_id) AS unique_orders
    FROM order_items;
    """,
    engine
)

   unique_orders
0          98666

In [31]:
payments = pd.read_csv('payments_clean.csv',)

payments.head(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [32]:
payments.shape

(103886, 5)

In [33]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [34]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [35]:
payments['payment_value'] = pd.to_numeric(payments['payment_value'],errors='coerce')

In [36]:
payments.duplicated(subset=['order_id','payment_sequential']).sum()

np.int64(0)

In [37]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [38]:
payments.to_sql(
    'payments',
    con=engine,
    if_exists='replace',
    index=False
)

103886

In [39]:
pd.read_sql(
    """
SELECT COUNT(*) total_payment_records
FROM payments;
""",
engine
)

   total_payment_records
0                 103886

In [40]:
pd.read_sql(
    """
    SELECT
        payment_type,
        COUNT(*) AS payment_records
    FROM payments
    GROUP BY payment_type
    ORDER BY payment_records DESC;
    """,
    engine
)

  payment_type  payment_records
0  credit_card            76795
1       boleto            19784
2      voucher             5775
3   debit_card             1529
4  not_defined                3

In [41]:
pd.read_sql(
    """
    SELECT
        SUM(payment_value) AS total_payment_value
    FROM payments;
    """,
    engine
)

   total_payment_value
0         1.600887e+07

In [42]:
products = pd.read_csv('products_clean.csv')

products.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [43]:
products.shape

(32951, 9)

In [44]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [45]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [46]:
numeric_cols = [
    'product_name_lenght',
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]

for col in numeric_cols:
    products[col] = pd.to_numeric(products[col],errors='coerce')

In [47]:
products.duplicated().sum()

np.int64(0)

In [48]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [49]:
products.to_sql(
    'products',
    con=engine,
    if_exists='replace',
    index=False
)

32951

In [50]:
pd.read_sql(
    """
SELECT *
FROM products
LIMIT 5;
""",
engine
)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [51]:
pd.read_sql(
    """
SELECT
    product_category_name,
    count(*) AS product_count
FROM products
GROUP BY product_category_name
ORDER By product_count DESC
LIMIT 10;   
""",
engine
)

    product_category_name  product_count
0         cama_mesa_banho           3029
1           esporte_lazer           2867
2        moveis_decoracao           2657
3            beleza_saude           2444
4   utilidades_domesticas           2335
5              automotivo           1900
6  informatica_acessorios           1639
7              brinquedos           1411
8      relogios_presentes           1329
9               telefonia           1134

In [52]:
sellers = pd.read_csv('sellers_clean.csv')

sellers.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP

In [53]:
sellers.shape

(3095, 4)

In [54]:
sellers.duplicated().sum()

np.int64(0)

In [55]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [56]:
sellers.to_sql(
    'sellers',
    con=engine,
    if_exists='replace',
    index=False
)

3095

In [57]:
pd.read_sql(
    """
SELECT count(*) AS total_sellers
FROM sellers;
""",
engine
)

   total_sellers
0           3095

In [58]:
pd.read_sql(
    """
SELECT *
FROM sellers
LIMIT 5;
""",
engine
)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP

In [59]:
pd.read_sql(
    """
SELECT 
  seller_state,
  COUNT(*) AS seller_count
FROM sellers
GROUP BY seller_state
ORDER BY seller_state DESC;
""",
engine
)

   seller_state  seller_count
0            SP          1849
1            SE             2
2            SC           190
3            RS           129
4            RO             2
5            RN             5
6            RJ           171
7            PR           349
8            PI             1
9            PE             9
10           PB             6
11           PA             1
12           MT             4
13           MS             5
14           MG           244
15           MA             1
16           GO            40
17           ES            23
18           DF            30
19           CE            13
20           BA            19
21           AM             1
22           AC             1

In [60]:
reviews = pd.read_csv('order_reviews_clean.csv')

reviews.head(2)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Title,No Review,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Title,No Review,2018-03-10 00:00:00,2018-03-11 03:05:13

In [61]:
reviews.shape

(99224, 7)

In [62]:
reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [63]:
review_data_col = [
     'review_creation_date',
    'review_answer_timestamp'
]

for col in review_data_col:
    reviews[col] = pd.to_datetime(reviews[col],errors='coerce')

In [64]:
reviews.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [65]:
reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [66]:
reviews[
    (reviews['review_score'] < 1) |
    (reviews['review_score'] > 5)
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [67]:
reviews.duplicated().sum()

np.int64(0)

In [68]:
reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [69]:
reviews.to_sql(
    'reviews',
    con=engine,
    if_exists='replace',
    index=False
)

99224

In [70]:
pd.read_sql(
    """
SELECT *
FROM reviews
LIMIT 5;
""",
engine
)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Title,No Review,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Title,No Review,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Title,No Review,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,No Title,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,No Title,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [71]:
pd.read_sql(
    """
SELECT 
   ROUND(AVG(review_score),2) AS average_review_score
FROM reviews;
""",
engine
)

   average_review_score
0                  4.09

In [72]:
category_translation = pd.read_csv('category_translation_clean.csv')

category_translation.head(3)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

In [73]:
category_translation.shape

(71, 2)

In [74]:
category_translation['product_category_name'].duplicated().sum()

np.int64(0)

In [75]:
category_translation['product_category_name_english'].duplicated().sum()

np.int64(0)

In [76]:
category_translation.duplicated().sum()

np.int64(0)

In [77]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [78]:
category_translation.to_sql(
    'category_translation',
    con=engine,
    if_exists='replace',
    index=False
)

71

In [79]:
pd.read_sql(
    """
SELECT *
FROM category_translation
LIMIT 5;
""",
engine
)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [80]:
tables_check = pd.read_sql(
    """
    SELECT
        'customers' AS table_name,
        COUNT(*) AS row_count
    FROM customers

    UNION ALL

    SELECT
        'orders',
        COUNT(*)
    FROM orders

    UNION ALL

    SELECT
        'order_items',
        COUNT(*)
    FROM order_items

    UNION ALL

    SELECT
        'payments',
        COUNT(*)
    FROM payments

    UNION ALL

    SELECT
        'products',
        COUNT(*)
    FROM products

    UNION ALL

    SELECT
        'sellers',
        COUNT(*)
    FROM sellers

    UNION ALL

    SELECT
        'reviews',
        COUNT(*)
    FROM reviews

    UNION ALL

    SELECT
        'category_translation',
        COUNT(*)
    FROM category_translation;
    """,
    engine
)

tables_check

             table_name  row_count
0             customers      99441
1                orders      99441
2           order_items     112650
3              payments     103886
4              products      32951
5               sellers       3095
6               reviews      99224
7  category_translation         71

# SQL Level 1 — Basic Business Analysis

This section answers basic business questions using the Olist e-commerce database.

In [81]:
# How many orders does Olist have

query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""
pd.read_sql(query,engine)

   total_orders
0         99441

In [82]:
# How many unique customers are there

query = """
SELECT COUNT(DISTINCT customer_unique_id) AS unique_customers
FROM customers;
"""

pd.read_sql(query,engine)

   unique_customers
0             96096

In [83]:
# 
# How many orders are delivered, canceled, shipped

query = """
SELECT
    order_status,
    COUNT(*) AS order_count
FROM orders
GROUP BY order_status
ORDER BY order_count DESC;
"""

pd.read_sql(query, engine)

  order_status  order_count
0    delivered        96478
1      shipped         1107
2     canceled          625
3  unavailable          609
4     invoiced          314
5   processing          301
6      created            5
7     approved            2

In [84]:
# What payment methods do customers use

query = """
SELECT
   payment_type,
   COUNT(*) AS payment_records
FROM payments
GROUP BY payment_type
ORDER BY payment_records DESC;
"""

pd.read_sql(query,engine)

  payment_type  payment_records
0  credit_card            76795
1       boleto            19784
2      voucher             5775
3   debit_card             1529
4  not_defined                3

In [85]:
# How satisfied are customers overall

query = """
SELECT 
    ROUND(AVG(review_score),2) AS average_review_score
FROM reviews;
"""

pd.read_sql(query,engine)

   average_review_score
0                  4.09

In [86]:
# How are review scores distributed

query = """
SELECT
   review_score,
   count(*) AS review_count
FROM reviews
GROUP BY review_score
ORDER BY review_score;
"""

pd.read_sql(query, engine)

   review_score  review_count
0             1         11424
1             2          3151
2             3          8179
3             4         19142
4             5         57328

SQL Level 1 — Basic Business Analysis
      
1. Total Orders
2. Unique Customers
3. Order Status Distribution
4. Payment Method Distribution
5. Average Review Score
6. Review Score Distribution

## SQL Level 2

In [87]:
# What is the total payment value generated by Olist
query = """
SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM payments;
"""

pd.read_sql(query, engine)

   total_revenue
0    16008872.12

In [88]:
# How much does a customer spend per order on average

query = """
SELECT
   ROUND(AVG(order_value),2) AS average_order_value
FROM(
SELECT
   order_id,
   SUM(payment_value) AS order_value
  FROM payments
  GROUP BY order_id
) AS order_totalS;
"""
pd.read_sql(query, engine)

   average_order_value
0               160.99

In [89]:
# Which Brazilian states generate the most revenue

query = """
SELECT
    c.customer_state,
    ROUND(SUM(p.payment_value), 2) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN payments p
    ON o.order_id = p.order_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

   customer_state  total_revenue
0              SP     5998226.96
1              RJ     2144379.69
2              MG     1872257.26
3              RS      890898.54
4              PR      811156.38
5              SC      623086.43
6              BA      616645.82
7              DF      355141.08
8              GO      350092.31
9              ES      325967.55
10             PE      324850.44
11             CE      279464.03
12             PA      218295.85
13             MT      187029.29
14             MA      152523.02
15             PB      141545.72
16             MS      137534.84
17             PI      108523.97
18             RN      102718.13
19             AL       96962.06
20             SE       75246.25
21             TO       61485.33
22             RO       60866.20
23             AM       27966.93
24             AC       19680.62
25             AP       16262.80
26             RR       10064.62

In [90]:
# Revenue by Product Category

query = """
SELECT
    ct.product_category_name_english AS category,
    ROUND(SUM(oi.price), 2) AS product_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
LEFT JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
GROUP BY ct.product_category_name_english
ORDER BY product_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

                category  product_revenue
0          health_beauty       1258681.34
1          watches_gifts       1205005.68
2         bed_bath_table       1036988.68
3         sports_leisure        988048.97
4  computers_accessories        911954.32
5        furniture_decor        729762.49
6             cool_stuff        635290.85
7             housewares        632248.66
8                   auto        592720.11
9           garden_tools        485256.46

In [91]:
# Which products generate the highest product sales
query = """
SELECT
    oi.product_id,
    ROUND(SUM(oi.price), 2) AS product_sales,
    COUNT(*) AS items_sold
FROM order_items oi
GROUP BY oi.product_id
ORDER BY product_sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

                         product_id  product_sales  items_sold
0  bb50f2e236e5eea0100680137654686c       63885.00         195
1  6cdd53843498f92890544667809f1595       54730.20         156
2  d6160fb7873f184099d9bc95e30376af       48899.34          35
3  d1c427060a0f73f6b889a5c7c61f2ac4       47214.51         343
4  99a4788cb24856965c36a24e339b6058       43025.56         488
5  3dd2a17168ec895c781a9191c1e95ad7       41082.60         274
6  25c38557cf793876c5abdd5931f922db       38907.32          38
7  5f504b3a1c75b73d6151be81eb05bdc9       37733.90          63
8  53b36df67ebb7c41585e8d54d6772e08       37683.42         323
9  aca2eb7d00ea1a7b8ebd4e68314663af       37608.90         527

In [92]:
# Which products generate the highest product sales

query = """
SELECT
    oi.seller_id,
    s.seller_city,
    s.seller_state,
    ROUND(SUM(oi.price),2) AS sales,
    COUNT(*) AS items_sold
FROM order_items oi
JOIN sellers s
    ON oi.seller_id = s.seller_id
GROUP BY 
    oi.seller_id,
    s.seller_city,
    s.seller_state
ORDER BY sales DESC
LIMIT 10;
"""
pd.read_sql(query,engine)

,seller_id,seller_city,seller_state,sales,items_sold
0,4869f7a5dfa277a7dca6462dcf3b52b2,Guariba,SP,229472.63,1156
1,53243585a1d6dc2643021fd1853d8905,Lauro De Freitas,BA,222776.05,410
2,4a3ca9315b744ce9f8e9374361493884,Ibitinga,SP,200472.92,1987
3,fa1c13f2614d7b5c4749cbc52fecda94,Sumare,SP,194042.03,586
4,7c67e1448b00f6e969d365cea6b010ab,Itaquaquecetuba,SP,187923.89,1364
5,7e93a43ef30c4f03f38b393420bc753a,Barueri,SP,176431.87,340
6,da8622b14eb17ae2831f4ac5b9dab84a,Piracicaba,SP,160236.57,1551
7,7a67c85e85bb2ce8582c35f2203ad736,Sao Paulo,SP,141745.53,1171
8,1025f0e2d44d7041d6cf58b6550e0bfa,Sao Paulo,SP,138968.55,1428
9,955fee9216a65b617aa5c0531780ce60,Sao Paulo,SP,135171.70,1499

# SQL Level 3

In [93]:
# How many orders does each customer place

query = """
SELECT
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_orders DESC;
"""

customer_orders = pd.read_sql(query, engine)

customer_orders.head(10)

                 customer_unique_id  total_orders
0  8d50f5eadf50201ccdcedfb9e2ac8455            17
1  3e43e6105506432c953e165fb2acf44c             9
2  1b6c7548a2a1f9037c1fd3ddfed95f33             7
3  6469f99c1f9dfae7733b25662e7f1782             7
4  ca77025e7201e3b30c44b472ff346268             7
5  f0e310a6839dce9de1638e0fe5ab282a             6
6  dc813062e0fc23409cd255f7f53c7074             6
7  de34b16117594161a6a89c50b289d35a             6
8  12f5d6e1cbf93dafd9dcc19095df0b3d             6
9  47c1a3033b8b77b3ab6e109eb4d5fdf3             6

In [94]:
# How many customers have purchased more than once
query = """
WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
)

SELECT
    COUNT(*) AS repeat_customers
FROM customer_orders
WHERE total_orders > 1;
"""

pd.read_sql(query, engine)

   repeat_customers
0              2997

A relatively low repeat-purchase rate suggests that customer retention is an important growth opportunity.

In [95]:
# Which customers have generated the highest total payment value
query = """
SELECT
    c.customer_unique_id,
    ROUND(SUM(p.payment_value), 2) AS lifetime_value,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN payments p
    ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY lifetime_value DESC
LIMIT 20;
"""

pd.read_sql(query, engine)

                  customer_unique_id  lifetime_value  total_orders
0   0a0a92112bd4c708ca5fde585afaa872        13664.08             1
1   46450c74a0d8c5ca9395da1daac6c120         9553.02             3
2   da122df9eeddfedc1dc1f5349a1a690c         7571.63             2
3   763c8b1c9c68a0229c42c9fc6f662b93         7274.88             1
4   dc4802a71eae9be1dd28f5d788ceb526         6929.31             1
5   459bef486812aa25204be022145caa62         6922.21             1
6   ff4159b92c40ebe40454e3e6a7c35ed6         6726.66             1
7   4007669dec559734d6f53e029e360987         6081.54             1
8   5d0a2980b292d049061542014e8960bf         4809.44             1
9   eebb5dda148d3893cdaf5b5ca3040ccb         4764.34             1
10  48e1ac109decbb87765a3eade6854098         4681.78             1
11  c8460e4251689ba205045f3ea17884a1         4655.91             4
12  edde2314c6c30e864a128ac95d6b2112         4513.32             1
13  a229eba70ec1c2abef51f04987deb7a5         4445.50             1
14  edf81e1f3070b9dac83ec83dacdbb9bc         4194.76             1
15  fa562ef24d41361e476e748681810e1e         4175.26             1
16  ca27f3dac28fb1063faddd424c9d95fa         4163.51             1
17  055ec572ac7f3c7bdd04a183830ebe59         4053.08             2
18  5e713be0853d8986528d7869a0811d2b         4042.74             1
19  58483a1c055dfb600f57c5b867174542         4034.44             1

In [96]:
# What product categories are strongest in each state?



query = """
SELECT
    c.customer_state,
    ct.product_category_name_english AS category,
    ROUND(SUM(oi.price), 2) AS sales
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
LEFT JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
GROUP BY
    c.customer_state,
    ct.product_category_name_english
ORDER BY
    c.customer_state,
    sales DESC;
"""

category_state = pd.read_sql(query, engine)

category_state.head(20)

   customer_state                category    sales
0              AC          sports_leisure  1677.46
1              AC           watches_gifts  1389.60
2              AC           health_beauty  1386.58
3              AC         furniture_decor  1316.44
4              AC   computers_accessories  1290.48
5              AC               computers  1200.00
6              AC               telephony  1103.96
7              AC                    baby   697.84
8              AC  books_general_interest   633.80
9              AC            garden_tools   629.00
10             AC          bed_bath_table   567.70
11             AC                    auto   540.98
12             AC              stationery   528.90
13             AC              housewares   513.06
14             AC             electronics   487.55
15             AC     luggage_accessories   348.90
16             AC               perfumery   303.88
17             AC           fashion_shoes   295.60
18             AC          consoles_games   276.14
19             AC                    toys   234.79

In [97]:
# Which sellers have the highest sales and how many items do they sell

query = """
SELECT
   oi.seller_id,
   s.seller_city,
   s.seller_state,
   ROUND(SUM(oi.price), 2) AS sales,
   COUNT(*) AS items_sold
FROM order_items oi
JOIN sellers s
   ON oi.seller_id = s.seller_id
GROUP BY
   oi.seller_id,
   s.seller_city,
   s.seller_state
ORDER BY sales DESC
LIMIT 20;
"""
pd.read_sql(query,engine)

,seller_id,seller_city,seller_state,sales,items_sold
0,4869f7a5dfa277a7dca6462dcf3b52b2,Guariba,SP,229472.63,1156
1,53243585a1d6dc2643021fd1853d8905,Lauro De Freitas,BA,222776.05,410
2,4a3ca9315b744ce9f8e9374361493884,Ibitinga,SP,200472.92,1987
3,fa1c13f2614d7b5c4749cbc52fecda94,Sumare,SP,194042.03,586
4,7c67e1448b00f6e969d365cea6b010ab,Itaquaquecetuba,SP,187923.89,1364
5,7e93a43ef30c4f03f38b393420bc753a,Barueri,SP,176431.87,340
6,da8622b14eb17ae2831f4ac5b9dab84a,Piracicaba,SP,160236.57,1551
7,7a67c85e85bb2ce8582c35f2203ad736,Sao Paulo,SP,141745.53,1171
8,1025f0e2d44d7041d6cf58b6550e0bfa,Sao Paulo,SP,138968.55,1428
9,955fee9216a65b617aa5c0531780ce60,Sao Paulo,SP,135171.70,1499
10,46dc3b2cc0980fb8ec44634e21d2718e,Rio De Janeiro,RJ,128111.19,542
11,6560211a19b47992c3666cc44a7e94c0,Sao Paulo,SP,123304.83,2033
12,620c87c171fb2a6dd6e8bb4dec959fc6,Petropolis,RJ,114774.50,798
13,7d13fca15225358621be4086e1eb0964,Ribeirao Preto,SP,113628.97,578
14,5dceca129747e92ff8ef7a997dc4f8ca,Santa Barbara D´Oeste,SP,112155.53,346
15,1f50f920176fa81dab994f9023523100,Sao Jose Do Rio Preto,SP,106939.21,1931
16,cc419e0650a3c5ba77189a1882b7556a,Santo Andre,SP,104288.42,1775
17,a1043bafd471dff536d0c462352beb48,Ilicinea,MG,101901.16,770
18,3d871de0142ce09b7081e2b9d1733cb1,Campo Limpo Paulista,SP,94914.20,1147
19,edb1ef5e36e0c8cd84eb3c9b003e486d,Teresopolis,RJ,79284.55,175

In [98]:
# Which states have the longest average delivery times

query = """
SELECT
    c.customer_state,
    ROUND(
        AVG(
            TIMESTAMPDIFF(
                DAY,
                o.order_purchase_timestamp,
                o.order_delivered_customer_date
            )
        ),
        2
    ) AS average_delivery_days,
    COUNT(DISTINCT o.order_id) AS delivered_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE
    o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
HAVING COUNT(DISTINCT o.order_id) >= 500
ORDER BY average_delivery_days DESC;
"""

pd.read_sql(query, engine)

   customer_state  average_delivery_days  delivered_orders
0              PA                  23.32               946
1              MA                  21.12               717
2              CE                  20.82              1279
3              PB                  19.95               517
4              BA                  18.87              3256
5              PE                  17.97              1593
6              MT                  17.59               886
7              ES                  15.33              1995
8              MS                  15.19               701
9              GO                  15.15              1957
10             RJ                  14.85             12353
11             RS                  14.82              5344
12             SC                  14.48              3547
13             DF                  12.51              2080
14             MG                  11.54             11355
15             PR                  11.53              4923
16             SP                   8.30             40495

In [99]:
# Do late deliveries have lower customer ratings

query = """
SELECT
    CASE
        WHEN o.order_delivered_customer_date >
             o.order_estimated_delivery_date
            THEN 'Late'
        ELSE 'On Time/Early'
    END AS delivery_status,
    
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(AVG(r.review_score), 2) AS average_review_score

FROM orders o

JOIN reviews r
    ON o.order_id = r.order_id

WHERE
    o.order_delivered_customer_date IS NOT NULL

GROUP BY
    CASE
        WHEN o.order_delivered_customer_date >
             o.order_estimated_delivery_date
            THEN 'Late'
        ELSE 'On Time/Early'
    END;
"""

pd.read_sql(query, engine)

  delivery_status  orders  average_review_score
0            Late    7662                  2.57
1   On Time/Early   88168                  4.29

In [100]:
# Do customers who use more installments make larger purchases

query = """
SELECT
   payment_installments,
   COUNT(DISTINCT order_id) AS orders,
   ROUND(SUM(payment_value), 2) AS total_payment,
   ROUND(AVG(payment_value), 2) AS average_payment
FROM payments
GROUP BY payment_installments
ORDER BY payment_installments;
"""
pd.read_sql(query,engine)

    payment_installments  orders  total_payment  average_payment
0                      0       2         188.63            94.32
1                      1   49060     5907233.36           112.42
2                      2   12389     1579283.03           127.23
3                      3   10443     1491103.80           142.54
4                      4    7088     1163907.61           163.98
5                      5    5234      961174.30           183.47
6                      6    3916      822611.81           209.85
7                      7    1623      305157.39           187.67
8                      8    4253     1313423.34           307.74
9                      9     644      131015.92           203.44
10                    10    5315     2211577.34           415.09
11                    11      23        2873.44           124.93
12                    12     133       42783.24           321.68
13                    13      16        2407.40           150.46
14                    14      15        2519.44           167.96
15                    15      74       32970.93           445.55
16                    16       5        1463.47           292.69
17                    17       8        1396.82           174.60
18                    18      27       13135.05           486.48
19                    20      17       10468.63           615.80
20                    21       3         731.10           243.70
21                    22       1         228.71           228.71
22                    23       1         236.48           236.48
23                    24      18       10980.88           610.05

In [101]:
# customers whose total spending is above the average customer spending

query = """
WITH customer_spending AS (
    SELECT
        c.customer_unique_id,
        SUM(p.payment_value) AS total_spending
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN payments p
        ON o.order_id = p.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    customer_unique_id,
    ROUND(total_spending, 2) AS total_spending
FROM customer_spending
WHERE total_spending > (

    SELECT AVG(total_spending)
    FROM customer_spending
)
ORDER BY total_spending DESC
LIMIT 20;
"""

pd.read_sql(query, engine)

                  customer_unique_id  total_spending
0   0a0a92112bd4c708ca5fde585afaa872        13664.08
1   46450c74a0d8c5ca9395da1daac6c120         9553.02
2   da122df9eeddfedc1dc1f5349a1a690c         7571.63
3   763c8b1c9c68a0229c42c9fc6f662b93         7274.88
4   dc4802a71eae9be1dd28f5d788ceb526         6929.31
5   459bef486812aa25204be022145caa62         6922.21
6   ff4159b92c40ebe40454e3e6a7c35ed6         6726.66
7   4007669dec559734d6f53e029e360987         6081.54
8   5d0a2980b292d049061542014e8960bf         4809.44
9   eebb5dda148d3893cdaf5b5ca3040ccb         4764.34
10  48e1ac109decbb87765a3eade6854098         4681.78
11  c8460e4251689ba205045f3ea17884a1         4655.91
12  edde2314c6c30e864a128ac95d6b2112         4513.32
13  a229eba70ec1c2abef51f04987deb7a5         4445.50
14  edf81e1f3070b9dac83ec83dacdbb9bc         4194.76
15  fa562ef24d41361e476e748681810e1e         4175.26
16  ca27f3dac28fb1063faddd424c9d95fa         4163.51
17  055ec572ac7f3c7bdd04a183830ebe59         4053.08
18  5e713be0853d8986528d7869a0811d2b         4042.74
19  58483a1c055dfb600f57c5b867174542         4034.44

In [102]:
# Which product categories have the best and worst customer ratings

query = """
SELECT
    ct.product_category_name_english AS category,
    COUNT(DISTINCT r.review_id) AS reviews,
    ROUND(AVG(r.review_score), 2) AS average_review_score
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
LEFT JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN reviews r
    ON oi.order_id = r.order_id
GROUP BY ct.product_category_name_english
HAVING COUNT(DISTINCT r.review_id) >= 100
ORDER BY average_review_score DESC;
"""

category_reviews = pd.read_sql(query, engine)

category_reviews.head(10)

                 category  reviews  average_review_score
0  books_general_interest      508                  4.45
1         books_technical      259                  4.37
2              food_drink      226                  4.32
3     luggage_accessories     1030                  4.32
4           fashion_shoes      239                  4.23
5                    food      445                  4.22
6              stationery     2294                  4.19
7                pet_shop     1700                  4.19
8               computers      178                  4.18
9         home_appliances      747                  4.17

# SQL Level 4 — Advanced SQL Analysis

This section uses CTEs and window functions to perform advanced
customer, seller, revenue, and retention analysis.

In [103]:
# Who are the highest-performing sellers
query = """
WITH seller_sales AS (
   SELECT
      seller_id,
      ROUND(SUM(price), 2) AS total_sales
    FROM order_items
    GROUP BY seller_id
)

SELECT
   seller_id,
   total_sales,
   RANK() OVER(
        ORDER BY total_sales DESC
   ) AS sales_rank
FROM seller_sales
ORDER BY sales_rank
LIMIT 20;
"""

pd.read_sql(query, engine)

                           seller_id  total_sales  sales_rank
0   4869f7a5dfa277a7dca6462dcf3b52b2    229472.63           1
1   53243585a1d6dc2643021fd1853d8905    222776.05           2
2   4a3ca9315b744ce9f8e9374361493884    200472.92           3
3   fa1c13f2614d7b5c4749cbc52fecda94    194042.03           4
4   7c67e1448b00f6e969d365cea6b010ab    187923.89           5
5   7e93a43ef30c4f03f38b393420bc753a    176431.87           6
6   da8622b14eb17ae2831f4ac5b9dab84a    160236.57           7
7   7a67c85e85bb2ce8582c35f2203ad736    141745.53           8
8   1025f0e2d44d7041d6cf58b6550e0bfa    138968.55           9
9   955fee9216a65b617aa5c0531780ce60    135171.70          10
10  46dc3b2cc0980fb8ec44634e21d2718e    128111.19          11
11  6560211a19b47992c3666cc44a7e94c0    123304.83          12
12  620c87c171fb2a6dd6e8bb4dec959fc6    114774.50          13
13  7d13fca15225358621be4086e1eb0964    113628.97          14
14  5dceca129747e92ff8ef7a997dc4f8ca    112155.53          15
15  1f50f920176fa81dab994f9023523100    106939.21          16
16  cc419e0650a3c5ba77189a1882b7556a    104288.42          17
17  a1043bafd471dff536d0c462352beb48    101901.16          18
18  3d871de0142ce09b7081e2b9d1733cb1     94914.20          19
19  edb1ef5e36e0c8cd84eb3c9b003e486d     79284.55          20

In [104]:
# Who are the top 3 sellers within each seller state
query = """
WITH seller_sales AS (
    SELECT
        oi.seller_id,
        s.seller_state,
        ROUND(SUM(oi.price), 2) AS total_sales
    FROM order_items oi
    JOIN sellers s
        ON oi.seller_id = s.seller_id
    GROUP BY
        oi.seller_id,
        s.seller_state
),

ranked_sellers AS (
    SELECT
        seller_id,
        seller_state,
        total_sales,
        RANK() OVER (
            PARTITION BY seller_state
            ORDER BY total_sales DESC
        ) AS seller_rank
    FROM seller_sales
)

SELECT
    seller_state,
    seller_id,
    total_sales,
    seller_rank
FROM ranked_sellers
WHERE seller_rank <= 3
ORDER BY
    seller_state,
    seller_rank;
"""

top_sellers_state = pd.read_sql(query, engine)

top_sellers_state.head(20)

   seller_state                         seller_id  total_sales  seller_rank
0            AC  4be2e7f96b4fd749d52dff41f80e39dd       267.00            1
1            AM  327b89b872c14d1c0be7235ef4871685      1177.00            1
2            BA  53243585a1d6dc2643021fd1853d8905    222776.05            1
3            BA  c72de06d72748d1a0dfb2125be43ba63     17522.00            2
4            BA  75d34ebb1bd0bd7dde40dd507b8169c3     15048.28            3
5            CE  bbf9ad41dca6603e614efcdad7aab8c4      7846.00            1
6            CE  dbdd0ec73a4817971d962698f2fea022      6384.00            2
7            CE  8d79c8a04e42d722a75097ce5cbcf2ef      2777.72            3
8            DF  44073f8b7e41514de3b7815dd0237f4f     18729.64            1
9            DF  f3b80352b986ab4d1057a4b724be19d0     10505.10            2
10           DF  3c487ae8f8d7542beff5788e2e0aea83      9385.70            3
11           ES  001cca7ae9ae17fb1caed9dfb1094831     25080.03            1
12           ES  33dd941c27854f7625b968cc6195a552      6787.50            2
13           ES  15aac934c58d886785ac1b17953ea898      4353.90            3
14           GO  9d5a9018aee56acb367ba9c3f05d1d6a     10292.31            1
15           GO  750303a20e9c56b2a6bc45cdce0b897d      8085.00            2
16           GO  b410bdd36d5db7a65dcd42b7ead933b8      7726.90            3
17           MA  06a2c3af7b3aee5d69171b0e14f0ee87     36408.95            1
18           MG  a1043bafd471dff536d0c462352beb48    101901.16            1
19           MG  25c5c91f63607446a97b143d2d535d31     54679.22            2

In [116]:
# How much did revenue increase or decrease compared with the previous month

query = """
WITH monthly_revenue AS (
   SELECT
      DATE_FORMAT(
      o.order_purchase_timestamp,
      '%%Y-%%m'
      ) AS order_month,
      SUM(p.payment_value) AS revenue
    FROM orders o
    JOIN payments p
      ON o.order_id = p.order_id
    GROUP BY 
       DATE_FORMAT(
           order_purchase_timestamp,
           '%%Y-%%m'
           )
),

revenue_with_previous AS (
   SELECT
      order_month,
      revenue,
      LAG(revenue) OVER (
         ORDER BY order_month
      ) AS previous_month_revenue
    FROM monthly_revenue  
)
SELECT
    order_month,
    ROUND(revenue, 2) AS revenue,
    ROUND(previous_month_revenue, 2) AS previous_month_revenue,
    ROUND(
        (revenue - previous_month_revenue)
        / previous_month_revenue * 100,
        2
    ) AS growth_percentage
FROM revenue_with_previous
ORDER BY order_month;
"""

monthly_growth = pd.read_sql(query,engine)

monthly_growth

   order_month     revenue  previous_month_revenue  growth_percentage
0      2016-09      252.24                     NaN                NaN
1      2016-10    59090.48                  252.24           23326.29
2      2016-12       19.62                59090.48             -99.97
3      2017-01   138488.04                   19.62          705751.38
4      2017-02   291908.01               138488.04             110.78
5      2017-03   449863.60               291908.01              54.11
6      2017-04   417788.03               449863.60              -7.13
7      2017-05   592918.82               417788.03              41.92
8      2017-06   511276.38               592918.82             -13.77
9      2017-07   592382.92               511276.38              15.86
10     2017-08   674396.32               592382.92              13.84
11     2017-09   727762.45               674396.32               7.91
12     2017-10   779677.88               727762.45               7.13
13     2017-11  1194882.80               779677.88              53.25
14     2017-12   878401.48              1194882.80             -26.49
15     2018-01  1115004.18               878401.48              26.94
16     2018-02   992463.34              1115004.18             -10.99
17     2018-03  1159652.12               992463.34              16.85
18     2018-04  1160785.48              1159652.12               0.10
19     2018-05  1153982.15              1160785.48              -0.59
20     2018-06  1023880.50              1153982.15             -11.27
21     2018-07  1066540.75              1023880.50               4.17
22     2018-08  1022425.32              1066540.75              -4.14
23     2018-09     4439.54              1022425.32             -99.57
24     2018-10      589.67                 4439.54             -86.72

In [111]:
# How does cumulative revenue grow over time?

query = """
WITH monthly_revenue AS (
   SELECT
      DATE_FORMAT(
         o.order_purchase_timestamp,
         '%%Y-%%m'
      )AS order_month,
      SUM(p.payment_value) AS revenue
    FROM orders o
    JOIN payments p
       ON o.order_id = p.order_id
    GROUP BY
       DATE_FORMAT(
       o.order_purchase_timestamp,
       '%%Y-%%m'
       )
)

SELECT
   order_month,
   ROUND(revenue, 2) AS monthly_revenue,
   ROUND(
      SUM(revenue) OVER(
        ORDER BY order_month
      ),
      2
   )AS cumulative_revenue
FROM monthly_revenue
ORDER BY order_month;
"""

pd.read_sql(query, engine)

   order_month  monthly_revenue  cumulative_revenue
0      2016-09           252.24              252.24
1      2016-10         59090.48            59342.72
2      2016-12            19.62            59362.34
3      2017-01        138488.04           197850.38
4      2017-02        291908.01           489758.39
5      2017-03        449863.60           939621.99
6      2017-04        417788.03          1357410.02
7      2017-05        592918.82          1950328.84
8      2017-06        511276.38          2461605.22
9      2017-07        592382.92          3053988.14
10     2017-08        674396.32          3728384.46
11     2017-09        727762.45          4456146.91
12     2017-10        779677.88          5235824.79
13     2017-11       1194882.80          6430707.59
14     2017-12        878401.48          7309109.07
15     2018-01       1115004.18          8424113.25
16     2018-02        992463.34          9416576.59
17     2018-03       1159652.12         10576228.71
18     2018-04       1160785.48         11737014.19
19     2018-05       1153982.15         12890996.34
20     2018-06       1023880.50         13914876.84
21     2018-07       1066540.75         14981417.59
22     2018-08       1022425.32         16003842.91
23     2018-09          4439.54         16008282.45
24     2018-10           589.67         16008872.12

In [ ]:
# What percentage of total sales does each product category contribute

query = """
WITH category_sales AS (
    SELECT
        ct.product_category_name_english AS category,
        SUM(oi.price) AS sales
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    LEFT JOIN category_translation ct
        ON p.product_category_name =
           ct.product_category_name
    GROUP BY ct.product_category_name_english
)

SELECT
    category,
    ROUND(sales, 2) AS sales,
    ROUND(
        sales * 100.0 /
        SUM(sales) OVER (),
        2
    ) AS revenue_percentage
FROM category_sales
ORDER BY sales DESC;
"""

category_contribution = pd.read_sql(query, engine)

category_contribution.head(15)

                 category       sales  revenue_percentage
0           health_beauty  1258681.34                9.26
1           watches_gifts  1205005.68                8.87
2          bed_bath_table  1036988.68                7.63
3          sports_leisure   988048.97                7.27
4   computers_accessories   911954.32                6.71
5         furniture_decor   729762.49                5.37
6              cool_stuff   635290.85                4.67
7              housewares   632248.66                4.65
8                    auto   592720.11                4.36
9            garden_tools   485256.46                3.57
10                   toys   483946.60                3.56
11                   baby   411764.89                3.03
12              perfumery   399124.87                2.94
13              telephony   323667.53                2.38
14       office_furniture   273960.70                2.02

In [ ]:
# Who are the highest-value customers

query = """
WITH customer_sales AS (
    SELECT
        c.customer_unique_id,
        ROUND(SUM(p.payment_value), 2) AS total_spending
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN payments p
        ON o.order_id = p.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    customer_unique_id,
    total_spending,
    RANK() OVER (
        ORDER BY total_spending DESC
    ) AS customer_rank
FROM customer_sales
ORDER BY customer_rank
LIMIT 20;
"""

pd.read_sql(query, engine)

                  customer_unique_id  total_spending  customer_rank
0   0a0a92112bd4c708ca5fde585afaa872        13664.08              1
1   46450c74a0d8c5ca9395da1daac6c120         9553.02              2
2   da122df9eeddfedc1dc1f5349a1a690c         7571.63              3
3   763c8b1c9c68a0229c42c9fc6f662b93         7274.88              4
4   dc4802a71eae9be1dd28f5d788ceb526         6929.31              5
5   459bef486812aa25204be022145caa62         6922.21              6
6   ff4159b92c40ebe40454e3e6a7c35ed6         6726.66              7
7   4007669dec559734d6f53e029e360987         6081.54              8
8   5d0a2980b292d049061542014e8960bf         4809.44              9
9   eebb5dda148d3893cdaf5b5ca3040ccb         4764.34             10
10  48e1ac109decbb87765a3eade6854098         4681.78             11
11  c8460e4251689ba205045f3ea17884a1         4655.91             12
12  edde2314c6c30e864a128ac95d6b2112         4513.32             13
13  a229eba70ec1c2abef51f04987deb7a5         4445.50             14
14  edf81e1f3070b9dac83ec83dacdbb9bc         4194.76             15
15  fa562ef24d41361e476e748681810e1e         4175.26             16
16  ca27f3dac28fb1063faddd424c9d95fa         4163.51             17
17  055ec572ac7f3c7bdd04a183830ebe59         4053.08             18
18  5e713be0853d8986528d7869a0811d2b         4042.74             19
19  58483a1c055dfb600f57c5b867174542         4034.44             20

In [118]:
# When did each customer's first and latest order occur

query = """
SELECT
   c.customer_unique_id,
   MIN(o.order_purchase_timestamp) AS first_purchase,
   MAX(o.order_purchase_timestamp) AS last_purchase,
   COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
   ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_orders DESC;

"""

customer_history = pd.read_sql(query, engine)

customer_history.head(10)

,customer_unique_id,first_purchase,last_purchase,total_orders
0,8d50f5eadf50201ccdcedfb9e2ac8455,2017-05-15 23:30:03,2018-08-20 19:14:26,17
1,3e43e6105506432c953e165fb2acf44c,2017-09-18 18:53:15,2018-02-27 18:36:39,9
2,1b6c7548a2a1f9037c1fd3ddfed95f33,2017-11-13 16:44:41,2018-02-14 13:22:12,7
3,ca77025e7201e3b30c44b472ff346268,2017-10-09 12:34:39,2018-06-01 11:38:29,7
4,6469f99c1f9dfae7733b25662e7f1782,2017-09-19 01:02:44,2018-06-28 00:43:34,7
5,63cfc61cee11cbe306bff5857d00bfe4,2017-05-11 14:39:53,2018-05-28 17:20:02,6
6,47c1a3033b8b77b3ab6e109eb4d5fdf3,2017-08-07 14:14:22,2018-01-24 15:15:26,6
7,f0e310a6839dce9de1638e0fe5ab282a,2017-05-20 08:53:30,2018-04-05 09:04:45,6
8,dc813062e0fc23409cd255f7f53c7074,2017-07-01 04:22:21,2018-08-23 00:07:26,6
9,de34b16117594161a6a89c50b289d35a,2017-11-03 00:16:32,2018-01-17 23:34:21,6

In [119]:
# How much revenue comes from customers who purchased more than once

query = """
WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS order_count,
        SUM(p.payment_value) AS total_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN payments p
        ON o.order_id = p.order_id
    GROUP BY c.customer_unique_id
)

SELECT
    CASE
        WHEN order_count > 1
            THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END AS customer_type,

    COUNT(*) AS customers,
    ROUND(SUM(total_revenue), 2) AS revenue

FROM customer_orders

GROUP BY
    CASE
        WHEN order_count > 1
            THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END;
"""

pd.read_sql(query, engine)

       customer_type  customers      revenue
0  One-Time Customer      93098  15064849.41
1    Repeat Customer       2997    944022.71

In [121]:
# How does customer retention change based on the month they first purchased

query = """
WITH customer_first_purchase AS (
    SELECT
        c.customer_unique_id,
        MIN(
            DATE_FORMAT(
                o.order_purchase_timestamp,
                '%%Y-%%m'
            )
        ) AS cohort_month
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
),

customer_activity AS (
    SELECT DISTINCT
        c.customer_unique_id,
        DATE_FORMAT(
            o.order_purchase_timestamp,
            '%%Y-%%m'
        ) AS activity_month
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
)

SELECT
    fp.cohort_month,
    ca.activity_month,
    COUNT(DISTINCT ca.customer_unique_id) AS active_customers

FROM customer_first_purchase fp

JOIN customer_activity ca
    ON fp.customer_unique_id =
       ca.customer_unique_id

GROUP BY
    fp.cohort_month,
    ca.activity_month

ORDER BY
    fp.cohort_month,
    ca.activity_month;
"""

cohort_data = pd.read_sql(query, engine)

cohort_data.head(20)

   cohort_month activity_month  active_customers
0       2016-09        2016-09                 4
1       2016-10        2016-10               321
2       2016-10        2017-04                 1
3       2016-10        2017-07                 1
4       2016-10        2017-09                 1
5       2016-10        2017-11                 1
6       2016-10        2018-01                 1
7       2016-10        2018-03                 1
8       2016-10        2018-05                 2
9       2016-10        2018-06                 2
10      2016-12        2016-12                 1
11      2016-12        2017-01                 1
12      2017-01        2017-01               764
13      2017-01        2017-02                 3
14      2017-01        2017-03                 2
15      2017-01        2017-04                 1
16      2017-01        2017-05                 3
17      2017-01        2017-06                 1
18      2017-01        2017-07                 4
19      2017-01        2017-08                 1